### ISSUE TITLE
Server is kidnapping CPU cycles

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#45] opened 2022-09-18 17:19 UTC
**Describe the bug**
Version of the server 0.17.1, the server after a while reaches high level of CPU % taken, to my old macBookPro from 2012 is reaching 100% or more, I monitor the process using the tool _htop_ and filtering with the keywork _tankroyale_
The problem doesn't look to appear until a game is started but when happens doesn't matter if the game is aborted or the bots are disconnected/unbooted/killed, the server is getting hold of my CPU

**To Reproduce**
Assuming the problem is not just related to me, boot up a server, join some bots, run a  game, stop the game, un-run the bots. Monitor the CPU usage from the server on each step.

**Expected behavior**
server to use any CPU is required to him during the battle and releasing it when the battle is finished

**Screenshots**
_htop_ screenshots, ignore the blue higlighted row and fcus on the server row and the CPU% column

Server just started:
![Screenshot 2022-09-18 at 19 01 16](https://user-images.githubusercontent.com/1309932/190919402-2c9fa4c2-27a9-4296-bc85-6adc97a7b258.png)

Walls and Crazy joined
![Screenshot 2022-09-18 at 19 01 53](https://user-images.githubusercontent.com/1309932/190919435-d81feabb-d446-4246-bbe1-12b81f19391c.png)

Game started
![Screenshot 2022-09-18 at 19 02 14](https://user-images.githubusercontent.com/1309932/190919461-0ff014eb-52ec-40a9-b630-d1a50211ce7c.png)

Game aborted
![Screenshot 2022-09-18 at 19 02 35](https://user-images.githubusercontent.com/1309932/190919479-ed29f289-1eb2-4f33-8a18-3bac51541f90.png)

Bots killed (after the games i aborted in order to avoid any illegal disruption of the game)
![Screenshot 2022-09-18 at 19 02 52](https://user-images.githubusercontent.com/1309932/190919539-5b7b1305-b3f6-4cd6-9227-6fbdab7c7246.png)

**Desktop (please complete the following information):**
MacOS Catalina on MacBook Pro 13-inch Mid 2-12

**Java info:**
java 18.0.2.1 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

**extra**
running server with this command line:
`java -jar robocode/servers/robocode-tankroyale-server.jar --port=1234 --botSecrets=secret1 --controllerSecrets=secret2`
The server jar is the one prelevated from the _robocode-tankroyale-gui-0.17.1.jar_ upon extracting it

**Comment by flemming-n-larsen** [comment] 2022-09-19 20:16
@SirStone 
Have you experienced this issue only for version 0.17.1 or also on older versions of the server. Version 0.17.1 had very few changes compared to version 0.17.0. Only the stuff with session-id etc. was changed, and should not be enough to hurt performance.

I have run the server with Java 18 on two machines:
- MacBook Pro 2019, 2,4Mhz, 8-core, Core I9
- PC with Windows 11 AMD Ryzen 5 5600G

And I ran from 8-30 bots at a time, with 30 TPS and ~900 TPS (with turn timeout = 1 ms).
I have booted, unbooted, started battle from scratch, and restarted the server, but not rebooting it. I also tried out port 1234 instead of the default 7654.

I have been using IntelliJ Ultimate with profiling tools to monitor the server.
The results between the two machines were very close, and under heavy pressure with 30 bots at ~900 TPS, this is the result:

![unnamed](https://user-images.githubusercontent.com/2179727/191107813-1cd9360d-d2d9-42a5-bfe4-fa66e60ab1fc.png)

So I am wondering if my machines are simply very powerful, and hence I don't run into the issue.
Or perhaps something is troubling the server on your side?

In the very early days I had problems with bots that did not disconnect correctly from the server. But this should not be an issue anymore, and the connection to bots is kept as long as they are not stopped/disconnecting the server.

**Comment by SirStone** [comment] 2022-09-24 10:39
Hello
I already answered via e-mail but I can't see my message here, so I assume that my answer never reached here...
this was my message wrote the  19/09/2022:
```
I experienced this from 0.17.0 too. I can do more tests:
-Older version of the server
-running the GUI avoiding all my code influence

More people could participate with their experience in order to understand if my machine is an isolated case.

It just came in my mind that I experienced another thing, running with my interface so for now I can't completely say that it's not my fault.
Lately I run continuously a battle made of 2 round, after battle ends it is started again right away programmatically (I do this to get the results faster); after some time that I'm observing the battle, the graphic just hangs, aborting or starting a new battle generates the messages from the server for the controller but no more ticks are received.

I told you this only because could be related to the CPU kidnapping and some sub-process could be killed from the system.

Would you be interested in my game setup? Maybe I'm pushing in a wrong and unexpected way the timings of the game.
```

Today I'm here providing more screenshots, I've tested the very same steps with versions 0.17.0, 0.16.0, 0.15.0 and 0.14.0 and all shows the same behaviour
For each, in order:
1. server just started <-- CPU is low
2. bots joined <-- CPU is low
3. running game <-- CPU goes high
4. stopping game  <-- CPU remains high
5. bots left  <-- CPU still remains high

**0.17.0**
1. ![Screenshot 2022-09-24 at 11 28 01](https://user-images.githubusercontent.com/1309932/192092222-6bfcb968-31df-4da2-a88c-900fd9e7943b.png)
2. ![Screenshot 2022-09-24 at 11 33 32](https://user-images.githubusercontent.com/1309932/192092227-c83c3433-9c66-41b4-9ca2-d50f398ee7c1.png)
3. ![Screenshot 2022-09-24 at 11 33 55](https://user-images.githubusercontent.com/1309932/192092229-2de8833f-1ff3-4f14-a166-8daef55149b7.png)
4. ![Screenshot 2022-09-24 at 11 34 14](https://user-images.githubusercontent.com/1309932/192092231-b4f6f33a-9f18-4581-9e49-4edf8cd4da7c.png)
5. ![Screenshot 2022-09-24 at 11 34 30](https://user-images.githubusercontent.com/1309932/192092232-c8fdf4b4-e775-49d6-a028-1f35144e3b13.png)

**0.16.0**
1. ![Screenshot 2022-09-24 at 11 46 26](https://user-images.githubusercontent.com/1309932/192092270-a5c3907c-9353-4eae-a359-8cebdaa29fd4.png)
2. ![Screenshot 2022-09-24 at 11 47 27](https://user-images.githubusercontent.com/1309932/192092271-4ee06250-faae-4ea6-a2f3-032806650367.png)
3. ![Screenshot 2022-09-24 at 11 47 44](https://user-images.githubusercontent.com/1309932/192092272-d523fdbd-8a47-4ffa-afe9-f60a8075c1b1.png)
4. ![Screenshot 2022-09-24 at 11 48 02](https://user-images.githubusercontent.com/1309932/192092273-9aad7314-56f6-429f-a68d-bb417f67b065.png)
5. ![Screenshot 2022-09-24 at 11 48 20](https://user-images.githubusercontent.com/1309932/192092274-13e1f8a6-303f-465e-823d-3e3c46832437.png)

**0.15.0**
1. ![Screenshot 2022-09-24 at 11 50 36](https://user-images.githubusercontent.com/1309932/192092287-2bdb11de-6988-4811-8067-019aa856f8f4.png)
2. ![Screenshot 2022-09-24 at 11 51 13](https://user-images.githubusercontent.com/1309932/192092289-1b782c45-e212-4d82-b8f2-71fb258851a0.png)
3. ![Screenshot 2022-09-24 at 11 51 28](https://user-images.githubusercontent.com/1309932/192092290-92f6c245-0489-42d7-8f16-691ac102c759.png)
4. ![Screenshot 2022-09-24 at 11 51 46](https://user-images.githubusercontent.com/1309932/192092291-051e88db-ce03-4588-94cd-e9f76d7a6e78.png)
5. ![Screenshot 2022-09-24 at 11 52 04](https://user-images.githubusercontent.com/1309932/192092292-119cfe23-8f1e-4d74-bad8-b36a5dac829f.png)

**0.14.0**
1. ![Screenshot 2022-09-24 at 11 52 54](https://user-images.githubusercontent.com/1309932/192092301-472dbf14-b03e-4c11-9edc-aa9442c17c1b.png)
2. ![Screenshot 2022-09-24 at 11 53 36](https://user-images.githubusercontent.com/1309932/192092304-4915f740-c7a6-45b9-af7c-0dc35a91b53f.png)
3. ![Screenshot 2022-09-24 at 11 53 50](https://user-images.githubusercontent.com/1309932/192092305-132411af-1912-42f4-972f-7f885a1fce14.png)
4. ![Screenshot 2022-09-24 at 11 54 07](https://user-images.githubusercontent.com/1309932/192092307-b6d0e31e-4b89-4f83-a783-fddeb9fe760e.png)
5. ![Screenshot 2022-09-24 at 11 54 32](https://user-images.githubusercontent.com/1309932/192092308-21818b21-5d6d-4b63-a0a6-c6bf5f65cbe8.png)

**Test with the GUI**
I've noticed that running the GUI is not creating this effect, no need for screenshots, the CPU goes up when the battle starts but as soon STOP is used the CPU usage drops to the normality (for a not running game).

My two cents:
1. The server, when the game is aborted leaves some routine running
2. The GUI, when stopping a game, is calling something on the server (maybe killing/rebooting it?) that solves/hides the problem

**Comment by flemming-n-larsen** [comment] 2022-09-24 18:48
I guess the issue you experience has existed with the server for a long time, as it has not changed much since February where I put the stuff on GitHub. I basically just adjusted game logics, fixed bugs, and added a few things like secrets and session id.

When benchmarking the server, I always run it outside the GUI. But it should not make much difference, as the server, booter, bots are all started up in their own processes, and the processes are killed when stopping these.

Regarding...
1) Yes, it could be that some left overs are still taking up CPU when aborting a game. I will look into that. I think I already benchmarked this in IntelliJ, where it looked okay. I am wondering, if it could be the Java version that makes a difference? E.g. the garbage collection could work differently.

2) When the GUI is killing the process, it simple sends a single line containing the letter `q` for "quit". Then the server exits its own process.
The GUI controls the server via the [ServerProcess.kt](https://github.com/robocode-dev/tank-royale/blob/master/gui-app/src/main/kotlin/dev/robocode/tankroyale/gui/server/ServerProcess.kt) (line 78)
And the server reacts on input within [Server.kt](https://github.com/robocode-dev/tank-royale/blob/master/server/src/main/kotlin/Server.kt) (line 128)

The rest of the communication between the controller (GUI) and server is via websockets.

**Comment by flemming-n-larsen** [comment] 2022-09-24 19:29
I did a new benchmarking of the Server using the IntelliJ Ultimate profiler on my Windows 11 PC running Oracle JDK 18.0.1.1 on Windows 11, AMD Ryzen 5 5600G 3.90 GHz (not running in full speed):

![Skærmbillede 2022-09-24 210637](https://user-images.githubusercontent.com/2179727/192114754-8d0d27ad-7d13-4e0d-8c31-38061d4eb356.png)

I am running 8 java sample bots with 30 TPS and turn timeout on 5000 us.

Even though my machine might be faster than your Mac Book from 2012, it should not matter, as we should see a rise on CPU and heap memory over time. But on my machine, it is going back to normal when I abort or restart a battle, and the curves are stable.

Max heap memory used: 147 MiB
Max CPU usage (single thread): 5%

The server is running a single thread ([ServerProcess.kt](https://github.com/robocode-dev/tank-royale/blob/master/gui-app/src/main/kotlin/dev/robocode/tankroyale/gui/server/ServerProcess.kt) line 124) which is run to accept input from `stdin` (waiting for the `q` command)
A thread is being started and stopped with the [NanoTimer.kt](https://github.com/robocode-dev/tank-royale/blob/master/server/src/main/kotlin/dev/robocode/tankroyale/server/core/NanoTimer.kt) responsible for triggering a "new turn" event, when the timer is started and stopped for a battle. Even though this thread could be leaking (?), it should not take up lots of CPU resources for before it reaches thousands of threads.

- - - -
Regarding your battles...  You run only two bots in 30 TPS and perhaps the default turn timeout of 30000 us? If you get near 1000 us (1 ms), you should expect problems (due to timer resolutions etc.). How many battles are your starting and aborting to observe the issue, and over how long time? If it is the first few battles, then something is definitely off.

**Comment by SirStone** [comment] 2022-09-24 20:49
I will play with the game setup timing variables to see if something changes but right now...
_How many battles are your starting and aborting to observe the issue, and over how long time?_ always the first one, 100% of times
_and over how long time?_ starting the game and aborting it after 10 seconds, 1 second or 1 millisecond to me is producing the same high CPU never released effect.

For me this is not a stopping issue, is just one click for me to reboot the server and stop the problem and during the battle is taking high CPU either way.
Because you don't experience this I suggest to wait until I try on another machine and/or operative system and maybe someone else can input their experience as well.

**Comment by flemming-n-larsen** [comment] 2022-09-25 13:42
Yes, it sure would be great to hear if anybody else is experiencing this problem too.
And it would like to hear what you experience on another machine as well.

**Comment by stobias123** [comment] 2022-09-30 22:31
I see this same thing! My setup is a little different. Looks like this.

1. Server is in docker container (one container per "environment") 
2. I run multiple server instances at a time. 
3. Two bots per server. 30TPS.

If I leave the server idle after bots leave I end up with very high CPU utilization.

**Comment by flemming-n-larsen** [comment] 2022-10-01 20:31
@stobias123 Thank you for the feedback. 🙂

I realised that I focused too much on what was going on within the battles. But it seems like the issue is triggered _after_ the battle has ended or is aborted.
I am still not able to see 100% CPU usage on my system, but I do see it is using CPU when the game should have stopped running, which was definitely an issue.

I have had a deep look into the server, and I have fixed these issues on the server on the master branch, and these fixes comes with the next release:

- Game is now aborted, when the last bot participating in a battle is leaving (disconnecting). Hence, the battle could run in the background (with bots not moving), when all bots have left a battle. So this was a bug that needed a fix.
- Timer used for turn timeout was not stopped, when a battle had ended/aborted. I guess this was the real issue, or at least a part of it.
- Freeing heap memory used for storing game state when game is ended/aborted.

Freeing the heap memory was not really a bug, but by design (keeping state in order to save a record of the entire battle history later). Anyways, I am freeing up the memory when the game is over to memory is free when the server waits for a new battle.

I am not sure if (all) issues are fixed now. But at least some of it has been fixed by now, and we'll see with the coming release if this also works out for you guys.

**Comment by flemming-n-larsen** [comment] 2022-10-02 19:12
@SirStone, @stobias123 
I have now released version [0.17.3](https://github.com/robocode-dev/tank-royale/releases/tag/v0.17.3) with several fixes for the server. I hope this one fixes the issue(s).

**Comment by SirStone** [comment] 2022-10-08 16:58
:clap: this 0.17.3 solves the problem for me!

1. server just started <-- CPU is low
![Screenshot 2022-10-08 at 18 44 14](https://user-images.githubusercontent.com/1309932/194718604-4936f0ac-afd4-45df-86b2-9ce1ecb9adc8.png)
2. bots joined <-- CPU is low
![Screenshot 2022-10-08 at 18 44 55](https://user-images.githubusercontent.com/1309932/194718621-562886b1-b176-46c8-9080-479b712e4ac0.png)
3. running game <-- CPU goes high
![Screenshot 2022-10-08 at 18 45 12](https://user-images.githubusercontent.com/1309932/194718638-e5eade94-3a75-42bf-b7f5-04db6f4b69a5.png)
5. stopping game <-- CPU goes low!!!!
![Screenshot 2022-10-08 at 18 45 36](https://user-images.githubusercontent.com/1309932/194718652-4233f87e-43b2-4188-990c-a51766e83795.png)

I dno't even need to un-boot the bots to go back to normal CPU usage now. No modifications have been made by me that could tamper with the results, better wait for the others to confirm my results.

My guess is that the problem was with the "not stopped timer" you mentioned.

**Comment by flemming-n-larsen** [comment] 2022-10-08 17:41
@SirStone 
Thanks for the feedback. I am really happy that this issue is now nailed.
I am sure that is was the timer that caused the issue. I will close this issue now.

**Closed by flemming-n-larsen** 2022-10-08 17:41 UTC
Labels: bug

**Comment by SirStone** [comment] 2022-10-11 07:04
I experienced this from 0.17.0 too. I can do more tests:
-Older version of the server
-running the GUI avoiding all my code influence

More people could participate with their experience in order to understand
if my machine is an isolated case.

It just came in my mind that I experienced another thing, running with my
interface so for now I can't completely say that it's not my fault.
Lately I run continuously a battle made of 2 round, after battle ends it is
started again right away programmatically (I do this to get the results
faster); after some time that I'm observing the battle, the graphic just
hangs, aborting or starting a new battle generates the messages from the
server for the controller but no more ticks are received.

I told you this only because could be related to the CPU kidnapping and
some sub-process could be killed from the system.

Would you be interested in my game setup? Maybe I'm pushing in a wrong and
unexpected way the timings of the game.

Il Lun 19 Set 2022, 22:16 Flemming N. Larsen ***@***.***> ha
scritto:
