### ISSUE TITLE
NULL Pointer Exception running robocode-tankroyale-gui-0.14.2.jar in Java 18 Win 10

### ISSUE THREAD

**Issue by aurora126** [robocode-dev/tank-royale#38] opened 2022-08-05 21:07 UTC
**Describe the bug**
Running the latest 0.14.2 GUI Jar file produces an NULL Pointer exception.

**To Reproduce**
1. Download the robocode-tankroyale-gui-0.14.2.jar from the link in the latest releases page https://github.com/robocode-dev/tank-royale/releases.
2. Open a windows 10 command prompt 
3. Type "java -jar robocode-tankroyale-gui-0.14.2.jar"

**Error info**
C:\Robocode Tank Royale>java -jar robocode-tankroyale-gui-0.14.2.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at dev.robocode.tankroyale.gui.ui.control.ControlPanel.<clinit>(Unknown Source)
        at dev.robocode.tankroyale.gui.ui.MainWindow$MainPanel.<clinit>(Unknown Source)
        at dev.robocode.tankroyale.gui.ui.MainWindow.<clinit>(Unknown Source)
        at dev.robocode.tankroyale.gui.GuiAppKt.main(Unknown Source)
        at dev.robocode.tankroyale.gui.GuiAppKt.main(Unknown Source)
Caused by: java.lang.NullPointerException:  must not be null
        at dev.robocode.tankroyale.gui.settings.ConfigSettings.getTps(Unknown Source)
        at dev.robocode.tankroyale.gui.ui.tps.TpsSlider.<clinit>(Unknown Source)
        ... 5 more

**Expected behavior**
A null pointer wasn't expected.  I expected the GUI to open but it didn't.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 Pro

**Java info:**
 - Version: [can be found by writing `java -version` from the command-line]
- Vendor: Oracle

C:\Robocode Tank Royale>java -version
java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

**Additional context**
N/A

**Comment by flemming-n-larsen** [comment] 2022-08-06 13:53
Thank you for reporting this @aurora126 🙂

I can confirm that this seems to be an issue that must be fixed asap!

**Comment by flemming-n-larsen** [comment] 2022-08-06 14:04
A work-around is to create a file named `config.properties` beside the `robocode-tankroyale-gui-0.14.2.jar` with the following content:
```
tps=30
```

**Comment by flemming-n-larsen** [comment] 2022-08-07 19:19
This issue should be fixed with [release 0.14.3](https://github.com/robocode-dev/tank-royale/releases/tag/v0.14.3). 🙂

**Closed** 2022-08-09 20:42 UTC
Labels: bug
