### ISSUE TITLE
Battle not starting on Windows 11 and 10 after installing docker linux subsystem

### ISSUE THREAD

**Issue by martinezpenya** [robocode-dev/tank-royale#119] opened 2024-11-28 18:00 UTC
**Describe the bug**
I'm using robocode tankroyale in my classroom in windows and linux. Now my students with windows 10 and 11 can't start battle.
They recently installed the docker with linux subsystem.

**To Reproduce**
1. Start robocode
2. Add bots
3. Start battle
4. nothing happens

**Error info**
no error

**Expected behavior**
start battle with selected bots

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 and 10

**Java info:**
 - Version: some studets with 23, other 18...
- Vendor: OpenJDK

**Additional context**
We tried with 24.4 and 26.1

**Comment by flemming-n-larsen** [comment] 2024-11-30 18:14
@martinezpenya Thank you for reporting this issue.

Is the problem occurring outside Docker or within Docker? Or is is "just" happening after having installed Docker?

**Comment by martinezpenya** [comment] 2024-11-30 18:16
It's happening after having installed Docker.
Before this it works great.

**Comment by flemming-n-larsen** [comment] 2024-11-30 18:20
OK. This should be easy to reproduce. I will have a look. :+1:

**Comment by flemming-n-larsen** [comment] 2024-11-30 19:53
@martinezpenya I have just installed Docker Desktop on Windows 11 running on WSL 2, and I can reproduce the issue.
I don't know what causes it yet, but I will find out.

**Comment by martinezpenya** [comment] 2024-11-30 19:54
You're Super! thank you for your time!

**Comment by flemming-n-larsen** [comment] 2024-12-01 07:43
I discovered, that this "only" occurs for the Java bots, but not the .Net bots.
And the issue is within the Bot API for Java, when a bot needs to send a message to the server via its socket. The first message is "ready" when the bot is about to participate in the battle. The server waits for the signal from the bots, but times out as it does not receive a "ready" signal from the bots.

**Comment by martinezpenya** [comment] 2024-12-01 10:22
If I can help you in any way, let mi know.

**Comment by flemming-n-larsen** [comment] 2024-12-01 20:20
I found the bug in the Bot API for Java, and fixed it. 
The fix will be available with the next version of Robocode coming soon. 😊

**Comment by flemming-n-larsen** [comment] 2024-12-02 20:13
Fixed with version [0.27.0](https://github.com/robocode-dev/tank-royale/releases/tag/v0.27.0), just released.

**Comment by flemming-n-larsen** [comment] 2024-12-02 20:15
@martinezpenya Can you confirm the fix work for your students as well?

**Comment by martinezpenya** [comment] 2024-12-02 23:19
Yes of course I will... My next class with them is on thursday, i'll come back and confirm that 0.27.0 solves the issue. Thank you so much!.

**Comment by martinezpenya** [comment] 2024-12-05 15:02
Hi @flemming-n-larsen everything works like a charm again. Thank you for your time.
Is there any way to support your work? buy-me-a-coffe or something like this?
Thank you!

**Comment by flemming-n-larsen** [comment] 2024-12-05 19:32
@martinezpenya I am very happy to hear that! Thank you for reporting back! 😊

I haven't thought of [buy-me-a-coffe](https://buymeacoffee.com/). I will consider that.
Currently, I make Robocode for fun, and make sure to fix any issue that arise.

**Closed** 2024-12-05 19:32 UTC
Labels: bug
