### ISSUE TITLE
Battle does not restart

### ISSUE THREAD

**Issue by dEgolf** [robocode-dev/tank-royale#10] opened 2022-04-03 16:00 UTC
**Describe the bug**
When battling the "Target" and "Walls" C# sample robots, hitting "Restart" does not restart the battle.  Instead the battle ends but does not restart. In the resulting state, hitting Ctrl+B to start a new battle does not open up the appropriate menu. To start a new battle, I had to close and reopen the GUI.

**To Reproduce**
1. Run robocode-tankroyale-gui-0.11.0.jar
2. Press Ctrl+B.
3. Run Target and Walls (from sample-bots-csharp-0.11.0)
4. Click "Add All"
5. Click "Start Battle"
6. Click "Restart"
7. Observe that the battle does not restart

**Error info**
No error message is displayed, as far as I can tell.

**Expected behavior**
The battle restarts when I click "Restart".

**Desktop (please complete the following information):**
-Windows 10

**Java info:**
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

**Additional context**
This reproduces pretty consistently for me, but the issue does not occur every single time. While typing the steps up for this issue, I reproduced the problem several times. However, there was one time where the restart button _did_ work correctly. This occurred when I had left the battle creation menu open for some time before actually starting the battle.

Some configuration options I used:
initial-position-enabled=false
tps=30

**Comment by flemming-n-larsen** [comment] 2022-04-03 20:23
Thank you for reporting and providing the detailed decription. :+1:

I will have a look into this.
At first look, I have no problem restarting the battle when clicking the "Restart" button on the control panel, but the GUI does seem to have an issue when I select "Restart" from the menu.

I will have a look into this and fix it.

**Comment by beamer159** [comment] 2022-04-06 17:48
I had the same problem. Even with no robots loaded.

From a fresh install (no .properties files):

1. run robocode-tankroyale-gui-0.11.0.jar
2. Select Battle > Start Battle
3. Select OK on the Error window reporting no bot directory root
4. Select Dismiss on the Bot Root Directories Config window. No need to add anything to reproduce this error
5. Select Cancel on the Select Bots for Battle window
6. Select Battle > Start Battle. The window does not reappear for me

**Comment by flemming-n-larsen** [comment] 2022-04-06 22:26
@beamer159 I found this issue as well and is working on a fix with version 0.11.1.

**Comment by flemming-n-larsen** [comment] 2022-04-07 19:41
@dEgolf and @beamer159: I have now made a patch release for fixing the GUI.

Try out the patched GUI here: [robocode-tankroyale-gui-0.11.1.jar](https://github.com/robocode-dev/tank-royale/releases/download/v0.11.1/robocode-tankroyale-gui-0.11.1.jar)

**Comment by dEgolf** [comment] 2022-04-08 01:06
I tried out the new GUI (0.11.1) without updating the sample robots. Maybe I'm doing something simple wrong, but when I run a bot it doesn't seem to join anymore. For example, running Walls (from the 0.11.0 C# sample bots) adds Walls to "Running bots", but Walls never seems to show up in "Joined bots" afterwards for me.  (I waited for about two minutes.)

**Comment by beamer159** [comment] 2022-04-08 04:54
I am having the same problem as @dEgolf

https://i.imgur.com/qAL93Fq.gif

**Comment by beamer159** [comment] 2022-04-08 16:29
The problem seems to be better, but not 100% fixed. I can create a new battle, adding 2 sample robots, MyFirstRobot and SpinBot for example. While the battle is running, I can usually restart the battle successfully. However, maybe 1-5% of the time, clicking the restart button does not restart the battle, but instead stops the battle, and I cannot create new battles without closing the program.

When the program gets into this error state, I cannot "unjoin" robots. Stopping them from running locally does not remove them from the "Joined Bots" or "Selected Bots" window. Normally, the program is able to do this.

Additionally, after starting a new battle, clicking the restart button the first time consistently stops the battle instead of restarts the battle. Clicking the restart button subsequent times restarts the battle as expected.

Video demonstrating all three issues: https://i.imgur.com/GPrREhH.mp4
1. Restarting the battle the first time stops the battle instead of restarts
2. Sometimes, restarting the battle stops the battle and cannot be restarted afterwards
3. When the above error occurs, bots cannot unjoin

**Comment by flemming-n-larsen** [comment] 2022-04-08 18:03
@beamer159 Thank you for the video. I really helps to see the problem. 👍🙂
I guess the is some raise condition between the GUI and the client handling connections with the bots.

I will look into this, as it needs to be fixed.

**Comment by dEgolf** [comment] 2022-04-12 19:45
Great! I don't seem to experience this problem anymore when using v0.11.2. The battles seem to stop and restart as desired now, at least for me.

**Comment by flemming-n-larsen** [comment] 2022-04-12 22:19
I am happy to hear that. 🙂

**Closed by flemming-n-larsen** 2022-04-12 22:19 UTC
Labels: bug
